### ISSUE TITLE
Selenium test requests waiting for a slot when slots are available

### ISSUE THREAD

**Issue by criscodex** [zalando-incubator/zalenium#13]
I've managed to successfully start Zalenium using the following command:

`./zalenium.sh start --sauceLabsEnabled false --chromeContainers 2 --firefoxContainers 2 --maxDockerSeleniumContainers 4`

However, when I kick off a test run that sends the request to a remote webdriver running at localhost:4444, I see this:

<img width="856" alt="screen shot 2016-10-25 at 10 33 34 pm" src="https://cloud.githubusercontent.com/assets/9448431/19711409/8c885726-9b03-11e6-8357-c83aeecae5f9.png">

Here is some more debug info:

![screencapture-localhost-4444-grid-console-1477449569816](https://cloud.githubusercontent.com/assets/9448431/19711488/0e6b0112-9b04-11e6-9175-837c7aef1d56.png)

Any help would be appreciated.

**Comment by diemol** [comment]
Hi @criscodex, 

What you write there looks normal, when Zalenium starts with the options you entered, the DockerSeleniumStarterProxy registers (which is the node you see in your screenshot), and shortly afterwards the configured additional nodes will show up (in this case, 2 Chrome, 2 Firefox).

As soon the additional nodes show up, the pending requests will start getting processed.

I have put a small gif showing the process, so you can get the idea of what I mean.

![zalenium_demo](https://cloud.githubusercontent.com/assets/5992658/19727341/47dd659e-9b8f-11e6-814b-5b1a33b422cd.gif)
The gif gets cut, but you can see the whole thing [here](http://recordit.co/mp3jz6ZwWF).

You can also do a `docker ps` to see that the containers are getting created after starting Zalenium, to double check that it is actually working.

Please give it a try again and let me know if something is not working as expected.

**Comment by criscodex** [comment]
Hi @diemol 

The behaviour I see on my end is that the configured additional nodes never show up. `docker ps -a` lists no containers.

It looks like for some reason the `docker-selenium` containers don't get created on my end...

**Comment by diemol** [comment]
Can you please check the `logs` folder? Maybe the `stdout.zalenium.hub.log` shows some errors... If you find something, please paste it here.
Which docker version are you using?

**Comment by criscodex** [comment]
You are right -- the following error is repeated several times in `stdout.zalenium.hub.log`:

> 13:17:19.278 INFO - Launching Selenium Grid hub
log4j:WARN No appenders could be found for logger (org.seleniumhq.jetty9.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
13:17:19.962 INFO - Will listen on 4444
13:17:20.001 INFO - Will listen on 4444
13:17:20.060 INFO - Nodes should register to http://10.50.29.236:4444/grid/register/
13:17:20.060 INFO - Selenium Grid hub is up and running
13:17:21.245 INFO - [DS] Capabilities fetched from https://raw.githubusercontent.com/elgalu/docker-selenium/latest/capabilities.json
13:17:21.249 INFO - Registered a node http://10.50.29.236:30000
13:17:21.250 INFO - [DS] Setting up 2 Firefox nodes and 2 Chrome nodes ready to use.
13:17:22.046 ERROR - [DS] com.spotify.docker.client.exceptions.ImageNotFoundException: Image not found: elgalu/selenium
com.spotify.docker.client.exceptions.ImageNotFoundException: Image not found: elgalu/selenium
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:555)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:532)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:278)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.beforeRegistration(DockerSeleniumStarterRemoteProxy.java:133)
	at org.openqa.grid.internal.Registry.add(Registry.java:356)
	at org.openqa.grid.web.servlet.RegistrationServlet$1.run(RegistrationServlet.java:92)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/create: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1599)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1549)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:550)
	... 6 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

I am running Docker for Mac 1.12.1.  This error is most likely due to us not using the "latest" `docker-selenium` release; we are using "2.53.1z" instead, which is the last Selenium 2 release:

> $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
elgalu/selenium     2.53.1z             c301bc76361f        3 weeks ago         2.576 GB

**Comment by diemol** [comment]
I'll test it locally with that version of the `docker-selenium` image and I will let you know.

**Comment by diemol** [comment]
Yes, I get the same error when I do `docker pull elgalu/selenium:2.53.1z` instead of just `docker pull elgalu/selenium`.

I will check how to fix it and then another release.

**Comment by diemol** [comment]
HI @criscodex,

We have just released [version 0.4.0](https://github.com/zalando-incubator/zalenium/releases/tag/v0.4.0), which should solve this issue. It also has the record video feature (videos are always recorded now), so feel free to try it!

If you have some time, please help us with testing it in your environment.

Thanks for reporting this issue and let us know how it works.

**Comment by criscodex** [comment]
Great work!  The new 0.4.0 release fixes this issue -- thank you! 👍 

I've also noticed that the video recording works properly -- generating new mkv files every 5 minutes.

However, I'm wondering whether it would be possible to keep the video recording disabled by default (or the ability to disable it by passing a command-line parameter) as it's very CPU intensive; even more so when running several simultaneous test sessions.

Also, is VNC viewing enabled by default? I wasn't able to figure out how to watch the tests running in any of the 4 containers that Zalenium had created.

**Comment by diemol** [comment]
That's cool! I am glad it works now for you.

About disabling video recording, we were talking about it and we left if by default turned on in this release. Nevertheless I think it makes sense to have a configuration variable to set it on or off. This will be treated in a separate issue. Check #20

VNC is something else we need to think about, how to do it and so on... What the default behaviour should be, etc... We will treat this in a separate issue as well. See #21

Hopefully we can tackle these two things in the next couple of weeks. 

For now, I will close this issue, but if any related problem shows up, feel free to comment or reopen it.
