### ISSUE TITLE
Enable/disable video recording through a configuration variable

### ISSUE THREAD

**Issue by diemol** [zalando-incubator/zalenium#20]
Right now is always enabled by default, this is CPU intensive and it would be a better idea to have this feature with a toggle, so it is used only when desired.

**Comment by diemol** [comment]
Resolved in this release:
https://github.com/zalando-incubator/zalenium/releases/tag/2.53.1b

@criscodex, would be cool if you have some minutes to give it a try :)

I'll start working on https://github.com/zalando-incubator/zalenium/issues/11 next week.

**Comment by criscodex** [comment]
Well done! 👍 

Tried out the `2.53.1b` release with the following command:

> docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    dosel/zalenium start --videoRecordingEnabled false

Received the following errors in the output:

> (...)
Status: Downloaded newer image for dosel/zalenium:latest
./zalenium.sh: line 60: [: missing `]'
SAUCE_USERNAME environment variable is not set, cannot start Sauce Labs node, exiting...

1. The syntax error at line 60 in zalenium.sh
2. The docker container was not created because no `--sauceLabs` parameter was given

After I added the missing parameter, I got this:

> $ docker run --rm -ti --name grid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock dosel/zalenium start --videoRecordingEnabled false --sauceLabsEnabled false
./zalenium.sh: line 60: [: missing `]'
Starting Selenium Hub...
rm: cannot remove 'logs/*hub*.log': No such file or directory
16:21:37.587 INFO - Launching Selenium Grid hub
log4j:WARN No appenders could be found for logger (org.seleniumhq.jetty9.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
16:21:38.343 INFO - Will listen on 4444
Selenium Hub started!
rm: cannot remove 'logs/*node*.log': No such file or directory
Starting DockerSeleniumStarter node...
16:21:38.433 INFO - Will listen on 4444
16:21:38.567 INFO - Nodes should register to http://172.17.0.2:4444/grid/register/
16:21:38.567 INFO - Selenium Grid hub is up and running
16:21:38.665 INFO - Launching a Selenium Grid node
16:21:39.366 INFO - Java: Oracle Corporation 25.111-b14
16:21:39.367 INFO - OS: Linux 4.4.27-moby amd64
16:21:39.378 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
16:21:39.449 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
16:21:39.449 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
16:21:39.450 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:21:39.451 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
16:21:39.452 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
16:21:39.454 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
16:21:39.454 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
16:21:39.482 INFO - Version Jetty/5.1.x
16:21:39.485 INFO - Started HttpContext[/selenium-server,/selenium-server]
16:21:39.494 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@50de0926
16:21:39.494 INFO - Started HttpContext[/wd,/wd]
16:21:39.494 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
16:21:39.495 INFO - Started HttpContext[/,/]
16:21:39.498 INFO - Started SocketListener on 0.0.0.0:30000
16:21:39.498 INFO - Started org.openqa.jetty.jetty.Server@6737fd8f
16:21:39.499 INFO - Selenium Grid node is up and ready to register to the hub
16:21:39.544 INFO - Starting auto registration thread. Will try to register every 5000 ms.
16:21:39.545 INFO - Registering the node to the hub: http://localhost:4444/grid/register
16:21:45.086 INFO - [DS] Capabilities fetched from https://raw.githubusercontent.com/elgalu/docker-selenium/latest/capabilities.json
16:21:45.097 INFO - The node is registered to the hub and ready to use
16:21:45.103 INFO - Registered a node http://172.17.0.2:30000
16:21:45.104 INFO - [DS] Setting up 1 Firefox nodes and 1 Chrome nodes ready to use.
16:21:46.638 ERROR - [DS] com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 0d823b063f07fc59455bed0a1157a016188e04acc2c3c558fe954b1b7365f10c
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 0d823b063f07fc59455bed0a1157a016188e04acc2c3c558fe954b1b7365f10c
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:599)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:587)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:288)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.beforeRegistration(DockerSeleniumStarterRemoteProxy.java:135)
	at org.openqa.grid.internal.Registry.add(Registry.java:356)
	at org.openqa.grid.web.servlet.RegistrationServlet$1.run(RegistrationServlet.java:92)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/0d823b063f07fc59455bed0a1157a016188e04acc2c3c558fe954b1b7365f10c/start: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1903)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1864)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:595)
	... 6 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
16:21:46.900 ERROR - [DS] com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 06a8791877e80341e496b676d56a2e37522a39492019a125b3af12190f8a2e02
com.spotify.docker.client.exceptions.ContainerNotFoundException: Container not found: 06a8791877e80341e496b676d56a2e37522a39492019a125b3af12190f8a2e02
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:599)
	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:587)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.startDockerSeleniumContainer(DockerSeleniumStarterRemoteProxy.java:288)
	at de.zalando.tip.zalenium.proxy.DockerSeleniumStarterRemoteProxy.beforeRegistration(DockerSeleniumStarterRemoteProxy.java:138)
	at org.openqa.grid.internal.Registry.add(Registry.java:356)
	at org.openqa.grid.web.servlet.RegistrationServlet$1.run(RegistrationServlet.java:92)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/06a8791877e80341e496b676d56a2e37522a39492019a125b3af12190f8a2e02/start: 404
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1903)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1864)
	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:595)
	... 6 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:990)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
DockerSeleniumStarter node started!
Sauce Labs not enabled...

After I renamed my container to `zalenium` everything worked fine. ✅ 

> $ docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock dosel/zalenium start --videoRecordingEnabled false --sauceLabsEnabled false
./zalenium.sh: line 60: [: missing `]'
Starting Selenium Hub...
rm: cannot remove 'logs/*hub*.log': No such file or directory
16:43:07.154 INFO - Launching Selenium Grid hub
log4j:WARN No appenders could be found for logger (org.seleniumhq.jetty9.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
16:43:07.849 INFO - Will listen on 4444
Selenium Hub started!
rm: cannot remove 'logs/*node*.log': No such file or directory
Starting DockerSeleniumStarter node...
16:43:07.948 INFO - Will listen on 4444
16:43:08.095 INFO - Nodes should register to http://172.17.0.2:4444/grid/register/
16:43:08.095 INFO - Selenium Grid hub is up and running
16:43:08.217 INFO - Launching a Selenium Grid node
16:43:08.857 INFO - Java: Oracle Corporation 25.111-b14
16:43:08.857 INFO - OS: Linux 4.4.27-moby amd64
16:43:08.874 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
16:43:08.982 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
16:43:08.983 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
16:43:08.984 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:43:08.985 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
16:43:08.989 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
16:43:08.990 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
16:43:08.991 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
16:43:09.025 INFO - Version Jetty/5.1.x
16:43:09.028 INFO - Started HttpContext[/selenium-server,/selenium-server]
16:43:09.032 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@50de0926
16:43:09.032 INFO - Started HttpContext[/wd,/wd]
16:43:09.033 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
16:43:09.033 INFO - Started HttpContext[/,/]
16:43:09.036 INFO - Started SocketListener on 0.0.0.0:30000
16:43:09.036 INFO - Started org.openqa.jetty.jetty.Server@6737fd8f
16:43:09.037 INFO - Selenium Grid node is up and ready to register to the hub
16:43:09.080 INFO - Starting auto registration thread. Will try to register every 5000 ms.
16:43:09.081 INFO - Registering the node to the hub: http://localhost:4444/grid/register
16:43:14.618 INFO - [DS] Capabilities fetched from https://raw.githubusercontent.com/elgalu/docker-selenium/latest/capabilities.json
16:43:14.625 INFO - The node is registered to the hub and ready to use
16:43:14.630 INFO - Registered a node http://172.17.0.2:30000
16:43:14.632 INFO - [DS] Setting up 1 Firefox nodes and 1 Chrome nodes ready to use.
DockerSeleniumStarter node started!
Sauce Labs not enabled...
16:43:21.343 INFO - Registered a node http://localhost:40000
16:43:21.451 INFO - Registered a node http://localhost:40001





16:53:55.340 INFO - Got a request to create a new session: Capabilities [{marionette=false, browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]
16:53:55.341 INFO - Available nodes: [http://localhost:40000, http://localhost:40001, http://172.17.0.2:30000]
16:53:55.342 INFO - Trying to create a new session on node http://localhost:40000
16:53:55.343 INFO - Trying to create a new session on test slot {chrome_binary=/usr/bin/google-chrome-stable, seleniumProtocol=WebDriver, acceptSslCerts=true, browserName=chrome, maxInstances=1, version=53.0.2785.116, platform=LINUX}
16:53:55.351 INFO - localhost:40000 start-video: Video recording is disabled
16:54:27.999 INFO - localhost:40000 stop-video: Video recording is disabled
16:54:28.030 INFO - localhost:40000 Marking the node as down because it was stopped after 1 tests.
16:54:28.031 INFO - localhost:40000 Marking the node as down because it was stopped after 1 tests.
16:54:28.031 WARN - Cleaning up stale test sessions on the unregistered node http://localhost:40000

^CTrapped SIGTERM/SIGINT so shutting down Zalenium gracefully...
Stopping Hub...
Stopping DockerSeleniumStarter node...
Removing exited docker-selenium containers...
9a84398b4b4f
2cf734814df5

**Comment by diemol** [comment]
Thanks @criscodex for checking! 
Yes, it is quite important to name the container `zalenium` since the network is based on that, perhaps we can find a way in the future to avoid depending on the name.

Thanks for the logs as well, I spotted a small bash error that will be fixed soon.

**Comment by Chinnuganga** [comment]
Is there a way we can start and stop the video recording in Zalenium by adding any cookie parameter?
